### ISSUE TITLE
Breaks when used in browser with browserify

### ISSUE THREAD

**Issue by 0815fox** [tecfu/tty-table#22]
When using in browser with browserify, recent builds break with the message:
```
>> Error: Cannot find module 'spawn-sync' from './node_modules/cross-spawn'
```
The issue is, that there is no spawn-sync for browsers as spawning is not possible, I guess. So cross-spawn only works in node. I don't know if it was ever intended, but previous versions (until 2.2.x) worked great in the browsers console...
From Version 2.3.0 until the most recent versions, it does not work anymore.
```
$ npm ls cross-spawn
analyzer
└─┬ tty-table@2.5.3
  └─┬ yargs@8.0.2
    └─┬ os-locale@2.1.0
      └─┬ execa@0.7.0
        └── cross-spawn@5.1.0 
```
For now I am sticking with version 2.2.5, as my module must work in node.js and browsers, using the table as debug output.

**Comment by tecfu** [comment]
Which browser are you using? What version / OS?

**Comment by 0815fox** [comment]
Actually it breaks before, as browserify does not succeed to pack all dependencies into a bundle. It fails because the named dependency is not used optionally and cannot work in the browser.

⁣Gesendet mit TypeApp ​

**Comment by tecfu** [comment]
Commit https://github.com/tecfu/tty-table/commit/d2d762cfe66502c2fd4df924660d698bf7d07cf1 should fix this, as I've removed yargs to the browserify package ignore list. 

Could you check and see if version 2.5.4 fixes this?

**Comment by tecfu** [comment]
Still breaks after d2d762c.

**Comment by tecfu** [comment]
Browser colors work now that `chalk` has been replaced by `kleur` in the browser. 

To test locally using a containerized apache instance running on port 8070 as your webserver:

```sh
git clone https://github.com/tecfu/tty-table
cd tty-table
docker run -dit --name my-apache-app -p 8070:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4
```
In your browser navigate to http://localhost:8070/examples/browser-example.html
